BLOCK_SIZE = 128
SCALE = 0.3

BLOCK_SCALED = BLOCK_SIZE * SCALE

SCREEN_WIDTH = int(BLOCK_SCALED * 25)
SCREEN_HEIGHT = int(BLOCK_SCALED * 25)

MOVEMENT_SPEED = 10

FONT_SIZE = 20

FONT = 'assets/Halt.ttf'
